// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, port;

  express = require("express");

  app = express();

  app.use(express["static"](__dirname));

  app.get("/api/promised.json", function(req, res) {
    var responseJSON;
    responseJSON = {
      id: 123,
      user: "richard"
    };
    return res.json(responseJSON);
  });

  port = process.env.PORT || 3000;

  app.listen(port);

  console.log("listening on port " + port);

}).call(this);
