// Generated by CoffeeScript 1.6.3
(function() {
  describe("Promises", function() {
    return it("is resolved (testing promises sucks)", function(done) {
      var output;
      output = "";
      return getJSON("/api/promised.json").then(function(data) {
        return output += "JSON got back!";
      }, function(errorData) {
        expect(output).toEqual("JSON got back!", "** Promise failed **");
        return done("** promise failed **");
      }).then(function() {
        expect(output).toEqual("JSON got back!");
        return done();
      });
    });
  });

}).call(this);
