// Generated by CoffeeScript 1.6.3
(function() {
  describe("Liker", function() {
    return it("likes a post", function(done) {
      var expectation;
      $('#sandbox').html("<div id='post'><button id='like'>1</button></div>");
      new Liker();
      expectation = function() {
        expect($('#like').html()).toEqual("2");
        return done();
      };
      return $('#like').click(expectation).click();
    });
  });

}).call(this);
